import {
  people01,
  people02,
  people03,
  facebook,
  instagram,
  linkedin,
  twitter,
  airbnb,
  binance,
  coinbase,
  dropbox,
} from '../assets/LandingPage'

import {
  faTruck,
  faBoxesStacked,
  faNoteSticky,
  faCalendarDays,
  faStar,
  faShield,
  faPaperPlane,
} from '@fortawesome/free-solid-svg-icons'

import { truck2d, scooter2d } from '../assets/EmployeePage'
export const navLinks = [
  {
    id: 'home',
    title: 'Home',
  },
  {
    id: 'features',
    title: 'Features',
  },
  {
    id: 'product',
    title: 'Product',
  },
  {
    id: 'clients',
    title: 'Clients',
  },
]

export const features = [
  {
    id: 'feature-1',
    icon: faStar,
    title: 'Priority Handling',
    content:
      'We prioritize urgent deliveries, like medical shipments, ensuring they reach their destination as fast as possible.',
  },
  {
    id: 'feature-2',
    icon: faShield,
    title: '100% Secured',
    content:
      'We take proactive steps make sure your information and transactions are secure.',
  },
  {
    id: 'feature-3',
    icon: faPaperPlane,
    title: 'Swift Delivery',
    content:
      'With our expedited shipping services, your packages are swiftly transported to their destination, ensuring timely delivery.',
  },
]

export const feedback = [
  {
    id: 'feedback-1',
    content:
      'The delivery service provided is exceptional. They always deliver on time and with care. I highly recommend them!',
    name: 'Herman Jensen',
    title: 'Founder & Leader',
    img: people01,
  },
  {
    id: 'feedback-2',
    content:
      "I've been using MediTransit for all my deliveries, and they never disappoint. Reliable, efficient, and friendly service!",
    name: 'Steve Mark',
    title: 'Founder & Leader',
    img: people02,
  },
  {
    id: 'feedback-3',
    content:
      'The tracking system provided is fantastic. I can monitor my deliveries in real-time, which gives me peace of mind.',
    name: 'Kenn Gallagher',
    title: 'Founder & Leader',
    img: people03,
  },
]

export const stats = [
  {
    id: 'stats-1',
    title: 'User Active',
    value: '200+',
  },
  {
    id: 'stats-2',
    title: 'Trusted by Company',
    value: '3+',
  },
  {
    id: 'stats-3',
    title: 'Orders Delivered',
    value: '12853+',
  },
]

export const dashboard_stats = [
  {
    id: 'stats-1',
    title: 'Todays Delivery',
    value: 127,
    valueTitle: 'Orders',
    change: 150,
    icon: faTruck,
  },
  {
    id: 'stats-2',
    title: 'Monthly Delivery',
    value: 3829,
    valueTitle: 'Orders',
    change: 150,
    icon: faBoxesStacked,
  },
  {
    id: 'stats-3',
    title: 'Delivery Issue',
    value: 13,
    valueTitle: 'Reports',
    change: -10,
    icon: faNoteSticky,
  },
  {
    id: 'stats-4',
    title: 'Total Delivery',
    value: 13958,
    valueTitle: 'Orders',
    change: 120,
    icon: faCalendarDays,
  },
]

export const footerLinks = [
  {
    title: 'Useful Links',
    links: [
      {
        name: 'Content',
        link: 'https://www.hoobank.com/content/',
      },
      {
        name: 'How it Works',
        link: 'https://www.hoobank.com/how-it-works/',
      },
      {
        name: 'Create',
        link: 'https://www.hoobank.com/create/',
      },
      {
        name: 'Explore',
        link: 'https://www.hoobank.com/explore/',
      },
      {
        name: 'Terms & Services',
        link: 'https://www.hoobank.com/terms-and-services/',
      },
    ],
  },
  {
    title: 'Community',
    links: [
      {
        name: 'Help Center',
        link: 'https://www.hoobank.com/help-center/',
      },
      {
        name: 'Partners',
        link: 'https://www.hoobank.com/partners/',
      },
      {
        name: 'Suggestions',
        link: 'https://www.hoobank.com/suggestions/',
      },
      {
        name: 'Blog',
        link: 'https://www.hoobank.com/blog/',
      },
      {
        name: 'Newsletters',
        link: 'https://www.hoobank.com/newsletters/',
      },
    ],
  },
  {
    title: 'Partner',
    links: [
      {
        name: 'Our Partner',
        link: 'https://www.hoobank.com/our-partner/',
      },
      {
        name: 'Become a Partner',
        link: 'https://www.hoobank.com/become-a-partner/',
      },
    ],
  },
]

export const socialMedia = [
  {
    id: 'social-media-1',
    icon: instagram,
    link: 'https://www.instagram.com/',
  },
  {
    id: 'social-media-2',
    icon: facebook,
    link: 'https://www.facebook.com/',
  },
  {
    id: 'social-media-3',
    icon: twitter,
    link: 'https://www.twitter.com/',
  },
  {
    id: 'social-media-4',
    icon: linkedin,
    link: 'https://www.linkedin.com/',
  },
]

export const clients = [
  {
    id: 'client-1',
    logo: airbnb,
  },
  {
    id: 'client-2',
    logo: binance,
  },
  {
    id: 'client-3',
    logo: coinbase,
  },
  {
    id: 'client-4',
    logo: dropbox,
  },
]

export const deliveryStatus = [
  { id: 1, title: 'On Progress' },
  { id: 2, title: 'Delivered' },
  { id: 3, title: 'On Hold' },
  { id: 4, title: 'Canceled' },
]

export const shipments = [
  {
    id: 1,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: null,
    orders_id: [1, 2, 3],
    packer_id: 1,
    driver_id: 6,
    vehicle_id: 1,
    status: 'On Progress',
  },
  {
    id: 2,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: '12 April 2024',
    orders_id: [4, 5],
    packer_id: 1,
    driver_id: 7,
    vehicle_id: 1,
    status: 'On Hold',
  },
  {
    id: 3,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: '12 April 2024',
    orders_id: [6],
    packer_id: 1,
    driver_id: 7,
    vehicle_id: 1,
    status: 'On Hold',
  },
  {
    id: 4,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: '12 April 2024',
    orders_id: [7, 8],
    packer_id: 1,
    driver_id: 1,
    vehicle_id: 1,
    status: 'On Progress',
  },
  {
    id: 5,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: '12 April 2024',
    orders_id: [9],
    packer_id: 1,
    driver_id: 4,
    vehicle_id: 2,
    status: 'Canceled',
  },
  {
    id: 6,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: '12 April 2024',
    orders_id: [10, 11, 12],
    packer_id: 1,
    driver_id: 6,
    vehicle_id: 2,
    status: 'On Progress',
  },
  {
    id: 7,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: '12 April 2024',
    orders_id: [13],
    packer_id: 1,
    driver_id: 6,
    vehicle_id: 2,
    status: 'On Progress',
  },
  {
    id: 8,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: '12 April 2024',
    orders_id: [14, 15],
    packer_id: 1,
    driver_id: 1,
    vehicle_id: 2,
    status: 'On Hold',
  },
  {
    id: 9,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: '12 April 2024',
    orders_id: [16, 17, 18],
    packer_id: 1,
    driver_id: 7,
    vehicle_id: 2,
    status: 'Delivered',
  },
  {
    id: 10,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: '12 April 2024',
    orders_id: [19, 20, 21, 22],
    packer_id: 1,
    driver_id: 7,
    vehicle_id: 2,
    status: 'On Hold',
  },
  {
    id: 11,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: '12 April 2024',
    orders_id: [23],
    packer_id: 1,
    driver_id: 6,
    vehicle_id: 5,
    status: 'On Hold',
  },
  {
    id: 12,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: '12 April 2024',
    orders_id: [24, 25],
    packer_id: 1,
    driver_id: 5,
    vehicle_id: 5,
    status: 'On Progress',
  },
  {
    id: 13,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: null,
    orders_id: [26],
    packer_id: 1,
    driver_id: 8,
    vehicle_id: 5,
    status: 'On Progress',
  },
  {
    id: 14,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: '12 April 2024',
    orders_id: [27],
    packer_id: 1,
    driver_id: 7,
    vehicle_id: 5,
    status: 'Delivered',
  },
  {
    id: 15,
    departure_date: '10 April 2024',
    estimated_completion_date: '12 April 2024',
    completion_date: null,
    orders_id: [28, 29, 30],
    packer_id: 1,
    driver_id: 5,
    vehicle_id: 5,
    status: 'Delivered',
  },
]

export const orders = [
  {
    id: 1,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'On Route',
    address: 'Jujur Agung Rejeki. PT',
    customer_id: 5,
    items_id: [10, 6, 5],
  },
  {
    id: 2,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'On Route',
    address: 'Apotek Kimia Farma',
    customer_id: 6,
    items_id: [7],
  },
  {
    id: 3,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'On Route',
    address: 'Apotek Sehat Jaya',
    customer_id: 6,
    items_id: [1],
  },
  {
    id: 4,
    order_date: '5 April 2024',
    ETA: '13 April 2024',
    status: 'On Route',
    address: '4057 Summerview Parkway',
    customer_id: 1,
    items_id: [5],
  },
  {
    id: 5,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'On Route',
    address: '15 Quincy Place',
    customer_id: 1,
    items_id: [6],
  },
  {
    id: 6,
    order_date: '5 April 2024',
    ETA: '13 April 2024',
    status: 'Delivered',
    address: '5 Roth Crossing',
    customer_id: 2,
    items_id: [6],
  },
  {
    id: 7,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'Delivered',
    address: '46425 Bartelt Hill',
    customer_id: 3,
    items_id: [7],
  },
  {
    id: 8,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'Canceled',
    address: '1 Lillian Pass',
    customer_id: 7,
    items_id: [7],
  },
  {
    id: 9,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'Canceled',
    address: '0657 Oakridge Parkway',
    customer_id: 2,
    items_id: [3],
  },
  {
    id: 10,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'On Hold',
    address: '4796 Monica Court',
    customer_id: 10,
    items_id: [10],
  },
  {
    id: 11,
    order_date: '5 April 2024',
    ETA: '13 April 2024',
    status: 'On Hold',
    address: '04213 Karstens Pass',
    customer_id: 3,
    items_id: [6],
  },
  {
    id: 12,
    order_date: '5 April 2024',
    ETA: '13 April 2024',
    status: 'On Hold',
    address: '1028 Cody Drive',
    customer_id: 6,
    items_id: [6],
  },
  {
    id: 13,
    order_date: '5 April 2024',
    ETA: '13 April 2024',
    status: 'Canceled',
    address: '9087 Village Lane',
    customer_id: 8,
    items_id: [2],
  },
  {
    id: 14,
    order_date: '5 April 2024',
    ETA: '13 April 2024',
    status: 'Canceled',
    address: '51 Center Trail',
    customer_id: 5,
    items_id: [10],
  },
  {
    id: 15,
    order_date: '5 April 2024',
    ETA: '13 April 2024',
    status: 'Delivered',
    address: '56192 Spaight Center',
    customer_id: 7,
    items_id: [1],
  },
  {
    id: 16,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'Canceled',
    address: '175 Gale Terrace',
    customer_id: 5,
    items_id: [5],
  },
  {
    id: 17,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'On Hold',
    address: '3974 Superior Court',
    customer_id: 5,
    items_id: [4],
  },
  {
    id: 18,
    order_date: '5 April 2024',
    ETA: '13 April 2024',
    status: 'Delivered',
    address: '41085 Dwight Point',
    customer_id: 6,
    items_id: [9],
  },
  {
    id: 19,
    order_date: '5 April 2024',
    ETA: '13 April 2024',
    status: 'Delivered',
    address: '4066 School Street',
    customer_id: 2,
    items_id: [7],
  },
  {
    id: 20,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'On Hold',
    address: '488 Clyde Gallagher Avenue',
    customer_id: 10,
    items_id: [6],
  },
  {
    id: 21,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'On Hold',
    address: '9 Banding Road',
    customer_id: 1,
    items_id: [6],
  },
  {
    id: 22,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'On Route',
    address: '32 Starling Avenue',
    customer_id: 7,
    items_id: [10],
  },
  {
    id: 23,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'On Hold',
    address: '49305 5th Alley',
    customer_id: 2,
    items_id: [3],
  },
  {
    id: 24,
    order_date: '5 April 2024',
    ETA: '13 April 2024',
    status: 'On Hold',
    address: '2 Heffernan Place',
    customer_id: 10,
    items_id: [4],
  },
  {
    id: 25,
    order_date: '5 April 2024',
    ETA: '13 April 2024',
    status: 'On Hold',
    address: '43780 Upham Point',
    customer_id: 2,
    items_id: [9],
  },
  {
    id: 26,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'On Route',
    address: '85 Elka Point',
    customer_id: 1,
    items_id: [1],
  },
  {
    id: 27,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'On Route',
    address: '7 Maple Wood Trail',
    customer_id: 8,
    items_id: [8],
  },
  {
    id: 28,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'Canceled',
    address: '6864 Bultman Center',
    customer_id: 7,
    items_id: [8],
  },
  {
    id: 29,
    order_date: '5 April 2024',
    ETA: '13 April 2024',
    status: 'On Route',
    address: '757 Carberry Road',
    customer_id: 6,
    items_id: [7],
  },
  {
    id: 30,
    order_date: '5 April 2024',
    ETA: '12 April 2024',
    status: 'Delivered',
    address: '99 Glendale Park',
    customer_id: 4,
    items_id: [1],
  },
]

export const items = [
  {
    id: 1,
    name: 'Metformin Hydrochloride',
    weight: 0.1,
    price: 71268,
    stock: 80,
  },
  {
    id: 2,
    name: 'Spinach',
    weight: 1.0,
    price: 154573,
    stock: 87,
  },
  {
    id: 3,
    name: 'Dextrose Monohydrate, Sodium Chloride, Sodium Lactate, Calcium Chloride, Magnesium Chloride',
    weight: 0.6,
    price: 23535,
    stock: 78,
  },
  {
    id: 4,
    name: 'Antihemophilic Factor/von Willebrand Factor Complex (Human)',
    weight: 2.8,
    price: 127973,
    stock: 72,
  },
  {
    id: 5,
    name: 'OCTINOXATE and TITANIUM DIOXIDE',
    weight: 2.6,
    price: 100340,
    stock: 89,
  },
  {
    id: 6,
    name: 'Trandolapril',
    weight: 2.1,
    price: 12179,
    stock: 99,
  },
  {
    id: 7,
    name: 'ciprofloxacin hydrochloride',
    weight: 0.2,
    price: 292295,
    stock: 93,
  },
  {
    id: 8,
    name: 'potassium chloride',
    weight: 1.1,
    price: 180837,
    stock: 99,
  },
  {
    id: 9,
    name: 'MINERAL OIL,PETROLATUM,PHENYLEPHRINE',
    weight: 2.6,
    price: 243880,
    stock: 77,
  },
  {
    id: 10,
    name: 'White Alder',
    weight: 1.6,
    price: 283928,
    stock: 89,
  },
]
export const vehicles = [
  {
    id: 1,
    type: 'Truck',
    imgUrl: truck2d,
    plateNumber: 'NRK 1992 K',
    status: 'Ready',
    capacity: 300,
    weight: 250,
  },
  {
    id: 2,
    imgUrl: scooter2d,
    type: 'Scooter',
    plateNumber: 'ABC 1234',
    status: 'Idle',
    capacity: 50,
    weight: 0,
  },
  {
    id: 3,
    type: 'Truck',
    plateNumber: 'XYZ 5678',
    status: 'On Delivery',
    capacity: 300,
    weight: 185,
  },
  {
    id: 4,
    imgUrl: truck2d,
    plateNumber: 'DEF 9876',
    status: 'Maintenance',
    capacity: 50,
    weight: 0,
  },
  {
    id: 5,
    imgUrl: scooter2d,
    type: 'Scooter',
    plateNumber: 'GHI 5432',
    status: 'On Delivery',
    capacity: 50,
    weight: 45,
  },
]

export const employees = [
  {
    id: 1,
    name: 'Feodor Zute',
    email: 'fzute0@japanpost.jp',
    address: '117 Transport Way',
    phone: '+44 636 564 5916',
    age: 10,
    gender: 'Male',
    job_id: 2,
    employement_id: 1,
  },
  {
    id: 2,
    name: 'Gerick Heeks',
    email: 'gheeks1@mashable.com',
    address: '7 Farmco Alley',
    phone: '+505 726 242 1200',
    age: 10,
    gender: 'Male',
    job_id: 2,
    employement_id: 1,
  },
  {
    id: 3,
    name: 'Arv Gorvette',
    email: 'agorvette2@discovery.com',
    address: '2 Briar Crest Parkway',
    phone: '+598 369 317 7585',
    age: 11,
    gender: 'Male',
    job_id: 2,
    employement_id: 1,
  },
  {
    id: 4,
    name: 'Jackie Ishaki',
    email: 'jishaki3@bandcamp.com',
    address: '51597 Bashford Place',
    phone: '+86 537 809 5042',
    age: 12,
    gender: 'Female',
    job_id: 2,
    employement_id: 2,
  },
  {
    id: 5,
    name: 'Myles Peel',
    email: 'mpeel4@privacy.gov.au',
    address: '54232 Moulton Junction',
    phone: '+62 388 478 1503',
    age: 16,
    gender: 'Male',
    job_id: 1,
    employement_id: 1,
  },
  {
    id: 6,
    name: 'Claudianus Cisco',
    email: 'ccisco5@blog.com',
    address: '26 Monterey Drive',
    phone: '+66 292 249 9004',
    age: 15,
    gender: 'Male',
    job_id: 2,
    employement_id: 2,
  },
  {
    id: 7,
    name: 'Michal Fattore',
    email: 'mfattore6@amazon.de',
    address: '6 Esker Center',
    phone: '+86 199 562 1637',
    age: 19,
    gender: 'Female',
    job_id: 1,
    employement_id: 2,
  },
  {
    id: 8,
    name: 'Elsa Render',
    email: 'erender7@springer.com',
    address: '377 Anthes Court',
    phone: '+86 961 347 9523',
    age: 18,
    gender: 'Female',
    job_id: 2,
    employement_id: 1,
  },
]

export const jobRoles = [
  {
    id: 1,
    role: 'Driver',
    responsibility:
      'Drivers transport goods or passengers safely and efficiently adhering to traffic laws, and ensure timely deliveries.',
  },
  {
    id: 2,
    role: 'Packer',
    responsibility:
      'The packer securely and accurately packs items into vehicles, collaborating with the team for smooth delivery.',
  },
]

export const workTypes = [
  {
    id: 1,
    type: 'Part-Time',
    responsibility:
      'Part-Time Employees work flexible hours, contributing to tasks based on the roles selected',
  },
  {
    id: 2,
    type: 'Full-Time',
    responsibility:
      'Full-Time Employees work regular full-time hours, providing consistent support to the team.',
  },
]
export const customers = [
  {
    id: 1,
    username: 'ogomm0',
    password: 'gllgaoyG{?',
    name: 'Ogdan Gomm',
    email: 'ogomm0@xing.com',
    phone: '+216 224 980 9814',
    address: '3636 South Alley',
    DateofBirth: '05/01/1991',
    balance: 660764,
  },
  {
    id: 2,
    username: 'bedelheid1',
    password: "krzeoyvQ,p4'",
    name: 'Bogey Edelheid',
    email: 'bedelheid1@facebook.com',
    phone: '+48 552 898 8322',
    address: '842 Vidon Terrace',
    DateofBirth: '24/03/1999',
    balance: 273454,
  },
  {
    id: 3,
    username: 'mpilger2',
    password: 'mazhoiyHZry2%',
    name: 'Morgen Pilger',
    email: 'mpilger2@senate.gov',
    phone: '+358 914 969 5199',
    address: '22 Mccormick Way',
    DateofBirth: '31/08/2005',
    balance: 780656,
  },
  {
    id: 4,
    username: 'fyannikov3',
    password: 'yjcriumFm',
    name: 'Forbes Yannikov',
    email: 'fyannikov3@time.com',
    phone: '+996 575 978 1337',
    address: '0361 Twin Pines Way',
    DateofBirth: '23/01/1994',
    balance: 319720,
  },
  {
    id: 5,
    username: 'lhinrich4',
    password: 'afffnlxIC{0ogvS',
    name: 'Lenore Hinrich',
    email: 'lhinrich4@so-net.ne.jp',
    phone: '+62 712 805 0876',
    address: '8845 Kipling Trail',
    DateofBirth: '25/01/2000',
    balance: 233644,
  },
  {
    id: 6,
    username: 'bmcdavitt5',
    password: 'phtadzlH\\H',
    name: 'Beniamino McDavitt',
    email: 'bmcdavitt5@spotify.com',
    phone: '+389 149 191 4084',
    address: '379 Bartelt Circle',
    DateofBirth: '14/03/1998',
    balance: 164594,
  },
  {
    id: 7,
    username: 'srosewarne6',
    password: 'siybkikI>{aW}h',
    name: 'Saunders Rosewarne',
    email: 'srosewarne6@mac.com',
    phone: '+63 250 322 7537',
    address: '2090 Huxley Trail',
    DateofBirth: '05/11/2004',
    balance: 951272,
  },
  {
    id: 8,
    username: 'ybrettle7',
    password: 'vbigcduY',
    name: 'Yoshiko Brettle',
    email: 'ybrettle7@slideshare.net',
    phone: '+7 181 763 6200',
    address: '0 Tennessee Center',
    DateofBirth: '13/09/1993',
    balance: 235006,
  },
  {
    id: 9,
    username: 'rshotter8',
    password: 'rpqdcqyC@E',
    name: 'Ray Shotter',
    email: 'rshotter8@oracle.com',
    phone: '+34 289 515 7045',
    address: '33745 Mallard Trail',
    DateofBirth: '31/05/1999',
    balance: 747162,
  },
  {
    id: 10,
    username: 'starbard9',
    password: 'suacofsY(LdXuUR',
    name: 'Shana Tarbard',
    email: 'starbard9@prweb.com',
    phone: '+355 519 555 1960',
    address: '6102 Corscot Circle',
    DateofBirth: '10/11/2002',
    balance: 315775,
  },
]

export const driverStats = [
  {
    id: 'driverStats-1',
    title: 'Days on the Road',
    value: 61,
  },
  {
    id: 'driverStats-2',
    title: 'Completed Orders',
    value: 48,
  },
  {
    id: 'driverStats-3',
    title: 'Orders Delivered on Time',
    value: 42,
  },
  {
    id: 'driverStats-4',
    title: 'Status: In Route',
    value: 'Execute Order #78',
  },
]

export const driverRecentDeliveries = [
  {
    id: 1,
    date: '02-06-2024',
    totalRecipients: 6,
    totalKm: 15,
    totalWeight: 27,
  },
  {
    id: 2,
    date: '02-06-2024',
    totalRecipients: 6,
    totalKm: 15,
    totalWeight: 27,
  },
  {
    id: 3,
    date: '02-06-2024',
    totalRecipients: 6,
    totalKm: 15,
    totalWeight: 27,
  },
  {
    id: 4,
    date: '02-06-2024',
    totalRecipients: 6,
    totalKm: 15,
    totalWeight: 27,
  },
  {
    id: 5,
    date: '02-06-2024',
    totalRecipients: 6,
    totalKm: 15,
    totalWeight: 27,
  },
]

export const driverPersonalInfo = [
  {
    id: 1,
    img: 'pfp.png',
    firstName: 'John',
    lastName: 'Smith',
    gender: 'Male',
    email: 'johnsmith@gmail.com',
    birthday: '03-03-2024',
    age: '20',
    phone: '+62 812-7113-9285',
    employmentType: 'Full-Time',
    employmentDate: '21-02-2022',
    address:
      'Dublin village, Braginsky district, Gomel region, Republic of Belarus',
  },
]
