import {
  faTruck,
  faBoxesStacked,
  faNoteSticky,
  faCalendarDays,
  faStar,
  faShield,
  faPaperPlane,
} from '@fortawesome/free-solid-svg-icons'

import { truck2d, scooter2d } from '../assets/EmployeePage'
export const navLinks = [
  {
    id: 'home',
    title: 'Home',
  },
  {
    id: 'features',
    title: 'Features',
  },
  {
    id: 'product',
    title: 'Product',
  },
  {
    id: 'clients',
    title: 'Clients',
  },
]

export const features = [
  {
    id: 'feature-1',
    icon: faStar,
    title: 'Priority Handling',
    content:
      'We prioritize urgent deliveries, like medical shipments, ensuring they reach their destination as fast as possible.',
  },
  {
    id: 'feature-2',
    icon: faShield,
    title: '100% Secured',
    content:
      'We take proactive steps make sure your information and transactions are secure.',
  },
  {
    id: 'feature-3',
    icon: faPaperPlane,
    title: 'Swift Delivery',
    content:
      'With our expedited shipping services, your packages are swiftly transported to their destination, ensuring timely delivery.',
  },
]

export const stats = [
  {
    id: 'stats-1',
    title: 'User Active',
    value: '200+',
  },
  {
    id: 'stats-2',
    title: 'Trusted by Company',
    value: '3+',
  },
  {
    id: 'stats-3',
    title: 'Orders Delivered',
    value: '12853+',
  },
]

export const dashboard_stats = [
  {
    id: 'stats-1',
    title: 'Todays Delivery',
    value: 127,
    valueTitle: 'Orders',
    change: 150,
    icon: faTruck,
  },
  {
    id: 'stats-2',
    title: 'Monthly Delivery',
    value: 3829,
    valueTitle: 'Orders',
    change: 150,
    icon: faBoxesStacked,
  },
  {
    id: 'stats-3',
    title: 'Delivery Issue',
    value: 13,
    valueTitle: 'Reports',
    change: -10,
    icon: faNoteSticky,
  },
  {
    id: 'stats-4',
    title: 'Total Delivery',
    value: 13958,
    valueTitle: 'Orders',
    change: 120,
    icon: faCalendarDays,
  },
]

export const shipments2 = [
  {
    id: 1,
    departureDate: '2024-08-01T09:00',
    ETA: '2024-08-01T17:00',
    completionDate: '2024-08-01T16:00',
    orders: [
      {
        id: 1,
        customer_name: 'John Doe',
        status: 'Delivered',
        address: 'Jalan Raya Pasar Minggu Km.18, Jakarta',
        distance: 4,
      },
      {
        id: 2,
        customer_name: 'Jane Smith',
        status: 'In Transit',
        address: 'Jalan Kebon Kacang No. 23, Jakarta',
        distance: 12.8,
      },
    ],
    warehouseStart: 'Jalan Raya No. 1, Jakarta',
    warehouseEnd: 'Jalan Kebon Kacang No. 23, Bandung',
    packer: {
      id: 201,
      name: 'Alice Johnson',
      email: 'alice.johnson@gmail.com',
    },
    driver: {
      id: 301,
      name: 'Bob Smith',
      email: 'bob.smith@gmail.com',
    },
    vehicle: {
      plateNumber: 'B 1234 CD',
      type: 'Truck',
    },
    status: 'Delivered',
    totalWeight: 120.5,
    totalPrice: 15000000,
    totalDistance: 100,
  },
  {
    id: 2,
    departureDate: '2024-08-02T10:00',
    ETA: '2024-08-02T18:00',
    completionDate: null,
    orders: [
      {
        id: 4,
        customer_name: 'David Brown',
        status: 'In Transit',
        address: 'Jalan Sudirman No. 5, Medan',
        distance: 4,
      },
      {
        id: 5,
        customer_name: 'Claire Williams',
        status: 'In Transit',
        address: 'Jalan Diponegoro No. 67, Yogyakarta',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Sudirman No. 5, Medan',
    warehouseEnd: 'Jalan Diponegoro No. 67, Yogyakarta',
    packer: {
      id: 202,
      name: 'Claire Williams',
      email: 'claire.williams@gmail.com',
    },
    driver: {
      id: 302,
      name: 'Daniel Lee',
      email: 'daniel.lee@gmail.com',
    },
    vehicle: {
      plateNumber: 'C 5678 DE',
      type: 'Scooter',
    },
    status: 'In Transit',
    totalWeight: 45.0,
    totalPrice: 5000000,
    totalDistance: 75,
  },
  {
    id: 3,
    departureDate: '2024-08-03T08:00',
    ETA: '2024-08-03T12:00',
    completionDate: '2024-08-03T11:00',
    orders: [
      {
        id: 6,
        customer_name: 'Emily Clark',
        status: 'Delivered',
        address: 'Jalan Gatot Subroto No. 12, Jakarta',
        distance: 4,
      },
      {
        id: 7,
        customer_name: 'Michael Green',
        status: 'Delivered',
        address: 'Jalan Gajah Mada No. 89, Semarang',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Gatot Subroto No. 12, Jakarta',
    warehouseEnd: 'Jalan Gajah Mada No. 89, Semarang',
    packer: {
      id: 203,
      name: 'David Brown',
      email: 'david.brown@gmail.com',
    },
    driver: {
      id: 303,
      name: 'Ella Davis',
      email: 'ella.davis@gmail.com',
    },
    vehicle: {
      plateNumber: 'D 9101 FG',
      type: 'Truck',
    },
    status: 'Delivered',
    totalWeight: 80.0,
    totalPrice: 10000000,
    totalDistance: 150,
  },
  {
    id: 4,
    departureDate: '2024-08-04T11:00',
    ETA: '2024-08-04T15:00',
    completionDate: null,
    orders: [
      {
        id: 8,
        customer_name: 'Olivia Taylor',
        status: 'In Transit',
        address: 'Jalan Merdeka No. 77, Surabaya',
        distance: 4,
      },
      {
        id: 9,
        customer_name: 'James Wilson',
        status: 'In Transit',
        address: 'Jalan Pahlawan No. 34, Medan',
        distance: 4,
      },
      {
        id: 10,
        customer_name: 'Sophia Moore',
        status: 'In Transit',
        address: 'Jalan Raya No. 45, Bandung',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Merdeka No. 77, Surabaya',
    warehouseEnd: 'Jalan Pahlawan No. 34, Medan',
    packer: {
      id: 204,
      name: 'Emma Wilson',
      email: 'emma.wilson@gmail.com',
    },
    driver: {
      id: 304,
      name: 'Frank Moore',
      email: 'frank.moore@gmail.com',
    },
    vehicle: {
      plateNumber: 'E 3456 GH',
      type: 'Scooter',
    },
    status: 'In Transit',
    totalWeight: 60.0,
    totalPrice: 7500000,
    totalDistance: 120,
  },
  {
    id: 5,
    departureDate: '2024-08-05T12:00',
    ETA: '2024-08-05T20:00',
    completionDate: null,
    orders: [
      {
        id: 11,
        customer_name: 'Jacob Harris',
        status: 'Scheduled',
        address: 'Jalan Ahmad Yani No. 20, Yogyakarta',
        distance: 4,
      },
      {
        id: 12,
        customer_name: 'Mia Young',
        status: 'Scheduled',
        address: 'Jalan Sudirman No. 55, Jakarta',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Ahmad Yani No. 20, Yogyakarta',
    warehouseEnd: 'Jalan Sudirman No. 55, Jakarta',
    packer: {
      id: 205,
      name: 'Grace Taylor',
      email: 'grace.taylor@gmail.com',
    },
    driver: {
      id: 305,
      name: 'Henry White',
      email: 'henry.white@gmail.com',
    },
    vehicle: {
      plateNumber: 'F 6789 IJ',
      type: 'Truck',
    },
    status: 'Ready',
    totalWeight: 110.0,
    totalPrice: 14000000,
    totalDistance: 200,
  },
  {
    id: 6,
    departureDate: '2024-08-06T13:00',
    ETA: '2024-08-06T19:00',
    completionDate: null,
    orders: [
      {
        id: 13,
        customer_name: 'Ava Davis',
        status: 'Scheduled',
        address: 'Jalan Gadjah Mada No. 90, Jakarta',
        distance: 4,
      },
      {
        id: 14,
        customer_name: 'Liam Martinez',
        status: 'Scheduled',
        address: 'Jalan Gatot Subroto No. 42, Bandung',
        distance: 4,
      },
      {
        id: 15,
        customer_name: 'Isabella Brown',
        status: 'Scheduled',
        address: 'Jalan Merdeka No. 12, Surabaya',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Gadjah Mada No. 90, Jakarta',
    warehouseEnd: 'Jalan Gatot Subroto No. 42, Bandung',
    packer: {
      id: 206,
      name: 'Isaac Martinez',
      email: 'isaac.martinez@gmail.com',
    },
    driver: {
      id: 306,
      name: 'Judy Clark',
      email: 'judy.clark@gmail.com',
    },
    vehicle: {
      plateNumber: 'G 1234 KL',
      type: 'Scooter',
    },
    status: 'Ready',
    totalWeight: 35.0,
    totalPrice: 4000000,
    totalDistance: 90,
  },
  {
    id: 7,
    departureDate: '2024-08-07T07:00',
    ETA: '2024-08-07T14:00',
    completionDate: '2024-08-07T13:00',
    orders: [
      {
        id: 16,
        customer_name: 'Ethan Johnson',
        status: 'Delivered',
        address: 'Jalan Sudirman No. 89, Medan',
        distance: 4,
      },
      {
        id: 17,
        customer_name: 'Charlotte Taylor',
        status: 'Exception',
        address: 'Jalan Kebon Kacang No. 78, Surabaya',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Sudirman No. 89, Medan',
    warehouseEnd: 'Jalan Kebon Kacang No. 78, Surabaya',
    packer: {
      id: 207,
      name: 'Karen Walker',
      email: 'karen.walker@gmail.com',
    },
    driver: {
      id: 307,
      name: 'Larry Harris',
      email: 'larry.harris@gmail.com',
    },
    vehicle: {
      plateNumber: 'H 3456 MN',
      type: 'Truck',
    },
    status: 'Exception',
    totalWeight: 95.0,
    totalPrice: 12500000,
    totalDistance: 140,
  },
  {
    id: 8,
    departureDate: '2024-08-08T08:00',
    ETA: '2024-08-08T17:00',
    completionDate: null,
    orders: [
      {
        id: 18,
        customer_name: 'Sofia Lewis',
        status: 'Delayed',
        address: 'Jalan Ahmad Yani No. 55, Surabaya',
        distance: 4,
      },
      {
        id: 19,
        customer_name: 'Daniel Harris',
        status: 'Delayed',
        address: 'Jalan Merdeka No. 88, Bandung',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Ahmad Yani No. 55, Surabaya',
    warehouseEnd: 'Jalan Merdeka No. 88, Bandung',
    packer: {
      id: 208,
      name: 'Sophia Lewis',
      email: 'sophia.lewis@gmail.com',
    },
    driver: {
      id: 308,
      name: 'Michael Adams',
      email: 'michael.adams@gmail.com',
    },
    vehicle: {
      plateNumber: 'I 7890 OP',
      type: 'Scooter',
    },
    status: 'Delayed',
    totalWeight: 55.0,
    totalPrice: 6500000,
    totalDistance: 110,
  },
  {
    id: 9,
    departureDate: '2024-08-09T09:00',
    ETA: '2024-08-09T14:00',
    completionDate: null,
    orders: [
      {
        id: 20,
        customer_name: 'Lucas Wilson',
        status: 'Scheduled',
        address: 'Jalan Kebon Kacang No. 12, Jakarta',
        distance: 4,
      },
      {
        id: 21,
        customer_name: 'Aria Martinez',
        status: 'Scheduled',
        address: 'Jalan Gajah Mada No. 67, Yogyakarta',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Kebon Kacang No. 12, Jakarta',
    warehouseEnd: 'Jalan Gajah Mada No. 67, Yogyakarta',
    packer: {
      id: 209,
      name: 'James Wilson',
      email: 'james.wilson@gmail.com',
    },
    driver: {
      id: 309,
      name: 'Emily Young',
      email: 'emily.young@gmail.com',
    },
    vehicle: {
      plateNumber: 'J 9012 QR',
      type: 'Truck',
    },
    status: 'Scheduled',
    totalWeight: 75.0,
    totalPrice: 9000000,
    totalDistance: 160,
  },
  {
    id: 10,
    departureDate: '2024-08-10T10:00',
    ETA: '2024-08-10T18:00',
    completionDate: null,
    orders: [
      {
        id: 22,
        customer_name: 'Ella Young',
        status: 'Scheduled',
        address: 'Jalan Merdeka No. 56, Jakarta',
        distance: 4,
      },
      {
        id: 23,
        customer_name: 'Mason Lee',
        status: 'Scheduled',
        address: 'Jalan Ahmad Yani No. 24, Bandung',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Merdeka No. 56, Jakarta',
    warehouseEnd: 'Jalan Ahmad Yani No. 24, Bandung',
    packer: {
      id: 210,
      name: 'Isabella Brown',
      email: 'isabella.brown@gmail.com',
    },
    driver: {
      id: 310,
      name: 'Lucas Wilson',
      email: 'lucas.wilson@gmail.com',
    },
    vehicle: {
      plateNumber: 'K 1234 ST',
      type: 'Scooter',
    },
    status: 'Scheduled',
    totalWeight: 70.0,
    totalPrice: 8500000,
    totalDistance: 130,
  },
  {
    id: 11,
    departureDate: '2024-08-11T12:00',
    ETA: '2024-08-11T21:00',
    completionDate: null,
    orders: [
      {
        id: 24,
        customer_name: 'Benjamin Lee',
        status: 'Scheduled',
        address: 'Jalan Merdeka No. 32, Yogyakarta',
        distance: 4,
      },
      {
        id: 25,
        customer_name: 'Chloe Wilson',
        status: 'Scheduled',
        address: 'Jalan Sudirman No. 78, Jakarta',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Merdeka No. 32, Yogyakarta',
    warehouseEnd: 'Jalan Sudirman No. 78, Jakarta',
    packer: {
      id: 211,
      name: 'Logan Scott',
      email: 'logan.scott@gmail.com',
    },
    driver: {
      id: 311,
      name: 'Madison Lee',
      email: 'madison.lee@gmail.com',
    },
    vehicle: {
      plateNumber: 'L 2345 UV',
      type: 'Truck',
    },
    status: 'Scheduled',
    totalWeight: 85.0,
    totalPrice: 10500000,
    totalDistance: 170,
  },
  {
    id: 12,
    departureDate: '2024-08-12T07:00',
    ETA: '2024-08-12T15:00',
    completionDate: null,
    orders: [
      {
        id: 26,
        customer_name: 'Zoe Brown',
        status: 'Scheduled',
        address: 'Jalan Diponegoro No. 56, Medan',
        distance: 4,
      },
      {
        id: 27,
        customer_name: 'Oliver Moore',
        status: 'Scheduled',
        address: 'Jalan Merdeka No. 90, Surabaya',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Diponegoro No. 56, Medan',
    warehouseEnd: 'Jalan Merdeka No. 90, Surabaya',
    packer: {
      id: 212,
      name: 'Ella Davis',
      email: 'ella.davis@gmail.com',
    },
    driver: {
      id: 312,
      name: 'Nora Scott',
      email: 'nora.scott@gmail.com',
    },
    vehicle: {
      plateNumber: 'M 6789 WX',
      type: 'Scooter',
    },
    status: 'Scheduled',
    totalWeight: 50.0,
    totalPrice: 6000000,
    totalDistance: 140,
  },
  {
    id: 13,
    departureDate: '2024-08-13T11:00',
    ETA: '2024-08-13T20:00',
    completionDate: null,
    orders: [
      {
        id: 28,
        customer_name: 'Jackson Harris',
        status: 'Scheduled',
        address: 'Jalan Raya No. 89, Bandung',
        distance: 4,
      },
      {
        id: 29,
        customer_name: 'Lily Scott',
        status: 'Scheduled',
        address: 'Jalan Kebon Kacang No. 34, Jakarta',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Raya No. 89, Bandung',
    warehouseEnd: 'Jalan Kebon Kacang No. 34, Jakarta',
    packer: {
      id: 213,
      name: 'Samuel Harris',
      email: 'samuel.harris@gmail.com',
    },
    driver: {
      id: 313,
      name: 'Olivia Young',
      email: 'olivia.young@gmail.com',
    },
    vehicle: {
      plateNumber: 'N 7890 YZ',
      type: 'Truck',
    },
    status: 'Scheduled',
    totalWeight: 95.0,
    totalPrice: 12000000,
    totalDistance: 160,
  },
  {
    id: 14,
    departureDate: '2024-08-14T09:00',
    ETA: '2024-08-14T18:00',
    completionDate: null,
    orders: [
      {
        id: 30,
        customer_name: 'Sebastian Lee',
        status: 'Scheduled',
        address: 'Jalan Merdeka No. 14, Yogyakarta',
        distance: 4,
      },
      {
        id: 31,
        customer_name: 'Mia Wilson',
        status: 'Scheduled',
        address: 'Jalan Ahmad Yani No. 65, Jakarta',
        distance: 4,
      },
      {
        id: 32,
        customer_name: 'Ella White',
        status: 'Scheduled',
        address: 'Jalan Gatot Subroto No. 77, Bandung',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Merdeka No. 14, Yogyakarta',
    warehouseEnd: 'Jalan Ahmad Yani No. 65, Jakarta',
    packer: {
      id: 214,
      name: 'Aiden White',
      email: 'aiden.white@gmail.com',
    },
    driver: {
      id: 314,
      name: 'Hannah Miller',
      email: 'hannah.miller@gmail.com',
    },
    vehicle: {
      plateNumber: 'O 8901 AB',
      type: 'Scooter',
    },
    status: 'Scheduled',
    totalWeight: 80.0,
    totalPrice: 9500000,
    totalDistance: 130,
  },
  {
    id: 15,
    departureDate: '2024-08-15T08:00',
    ETA: '2024-08-15T17:00',
    completionDate: null,
    orders: [
      {
        id: 33,
        customer_name: 'Ethan Davis',
        status: 'Scheduled',
        address: 'Jalan Kebon Kacang No. 21, Surabaya',
        distance: 4,
      },
      {
        id: 34,
        customer_name: 'Charlotte Brown',
        status: 'Scheduled',
        address: 'Jalan Merdeka No. 48, Yogyakarta',
        distance: 4,
      },
      {
        id: 35,
        customer_name: 'Lucas Taylor',
        status: 'Scheduled',
        address: 'Jalan Raya No. 45, Jakarta',
        distance: 4,
      },
    ],
    warehouseStart: 'Jalan Kebon Kacang No. 21, Surabaya',
    warehouseEnd: 'Jalan Merdeka No. 48, Yogyakarta',
    packer: {
      id: 215,
      name: 'Emma Davis',
      email: 'emma.davis@gmail.com',
    },
    driver: {
      id: 315,
      name: 'William Clark',
      email: 'william.clark@gmail.com',
    },
    vehicle: {
      plateNumber: 'P 9012 CD',
      type: 'Truck',
    },
    status: 'Scheduled',
    totalWeight: 85.0,
    totalPrice: 11000000,
    totalDistance: 150,
  },
]

export const orders = [
  {
    id: 1,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'In Transit',
    customer: {
      id: 5,
      name: 'Jujur Agung Rejeki',
      email: 'jujur.agung@gmail.com',
      phone: '+62 812 3456 7890',
      address: 'Jl. Merdeka No.1, Jakarta, Indonesia',
    },
    items: [
      { id: 10, name: 'Paracetamol', price: 15000, qty: 2 },
      { id: 6, name: 'Amoxicillin', price: 25000, qty: 1 },
      { id: 5, name: 'Ibuprofen', price: 20000, qty: 3 },
    ],
  },
  {
    id: 2,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'In Transit',
    customer: {
      id: 6,
      name: 'Apotek Kimia Farma',
      email: 'kimiafarma@gmail.com',
      phone: '+62 813 2345 6789',
      address: 'Jl. Sudirman No.2, Bandung, Indonesia',
    },
    items: [{ id: 7, name: 'Ciprofloxacin', price: 30000, qty: 1 }],
  },
  {
    id: 3,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'In Transit',
    customer: {
      id: 6,
      name: 'Apotek Sehat Jaya',
      email: 'sehat.jaya@gmail.com',
      phone: '+62 814 5678 2345',
      address: 'Jl. Mangga No.3, Surabaya, Indonesia',
    },
    items: [{ id: 1, name: 'Aspirin', price: 12000, qty: 1 }],
  },
  {
    id: 4,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'In Transit',
    customer: {
      id: 1,
      name: 'Jaya Farma',
      email: 'jaya.farma@gmail.com',
      phone: '+62 815 6789 3456',
      address: 'Jl. Bali No.4, Denpasar, Indonesia',
    },
    items: [{ id: 5, name: 'Ibuprofen', price: 20000, qty: 1 }],
  },
  {
    id: 5,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'In Transit',
    customer: {
      id: 1,
      name: 'Apotek Makmur',
      email: 'apotek.makmur@gmail.com',
      phone: '+62 816 3456 7890',
      address: 'Jl. Hasanuddin No.5, Makassar, Indonesia',
    },
    items: [{ id: 6, name: 'Amoxicillin', price: 25000, qty: 2 }],
  },
  {
    id: 6,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Delivered',
    customer: {
      id: 2,
      name: 'Apotek Nusantara',
      email: 'nusantara.apotek@gmail.com',
      phone: '+62 817 2345 6789',
      address: 'Jl. Ahmad Yani No.6, Semarang, Indonesia',
    },
    items: [{ id: 6, name: 'Amoxicillin', price: 25000, qty: 1 }],
  },
  {
    id: 7,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'Delivered',
    customer: {
      id: 3,
      name: 'Apotek Keluarga',
      email: 'keluarga.apotek@gmail.com',
      phone: '+62 818 1234 5678',
      address: 'Jl. Kalimantan No.7, Yogyakarta, Indonesia',
    },
    items: [{ id: 7, name: 'Ciprofloxacin', price: 30000, qty: 1 }],
  },
  {
    id: 8,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'Canceled',
    customer: {
      id: 7,
      name: 'Apotek Prima',
      email: 'prima.apotek@gmail.com',
      phone: '+62 819 8765 4321',
      address: 'Jl. Papua No.8, Jayapura, Indonesia',
    },
    items: [{ id: 7, name: 'Ciprofloxacin', price: 30000, qty: 1 }],
  },
  {
    id: 9,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'Canceled',
    customer: {
      id: 2,
      name: 'Apotek Nusantara',
      email: 'nusantara.apotek@gmail.com',
      phone: '+62 817 2345 6789',
      address: 'Jl. Ahmad Yani No.6, Semarang, Indonesia',
    },
    items: [{ id: 3, name: 'Metformin', price: 18000, qty: 1 }],
  },
  {
    id: 10,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'Ready',
    customer: {
      id: 10,
      name: 'Apotek Sejahtera',
      email: 'sejahtera.apotek@gmail.com',
      phone: '+62 820 1234 5678',
      address: 'Jl. Sulawesi No.9, Palu, Indonesia',
    },
    items: [{ id: 10, name: 'Paracetamol', price: 15000, qty: 3 }],
  },
  {
    id: 11,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Ready',
    customer: {
      id: 3,
      name: 'Apotek Keluarga',
      email: 'keluarga.apotek@gmail.com',
      phone: '+62 818 1234 5678',
      address: 'Jl. Kalimantan No.7, Yogyakarta, Indonesia',
    },
    items: [{ id: 6, name: 'Amoxicillin', price: 25000, qty: 2 }],
  },
  {
    id: 12,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Ready',
    customer: {
      id: 6,
      name: 'Apotek Sehat Jaya',
      email: 'sehat.jaya@gmail.com',
      phone: '+62 814 5678 2345',
      address: 'Jl. Mangga No.3, Surabaya, Indonesia',
    },
    items: [{ id: 6, name: 'Amoxicillin', price: 25000, qty: 1 }],
  },
  {
    id: 13,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Canceled',
    customer: {
      id: 8,
      name: 'Apotek Rakyat',
      email: 'rakyat.apotek@gmail.com',
      phone: '+62 821 2345 6789',
      address: 'Jl. Sumatera No.10, Medan, Indonesia',
    },
    items: [{ id: 2, name: 'Simvastatin', price: 22000, qty: 1 }],
  },
  {
    id: 14,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Canceled',
    customer: {
      id: 5,
      name: 'Jujur Agung Rejeki',
      email: 'jujur.agung@gmail.com',
      phone: '+62 812 3456 7890',
      address: 'Jl. Merdeka No.1, Jakarta, Indonesia',
    },
    items: [{ id: 10, name: 'Paracetamol', price: 15000, qty: 1 }],
  },
  {
    id: 15,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Ready',
    customer: {
      id: 3,
      name: 'Apotek Keluarga',
      email: 'keluarga.apotek@gmail.com',

      phone: '+62 818 1234 5678',
      address: 'Jl. Kalimantan No.7, Yogyakarta, Indonesia',
    },
    items: [{ id: 9, name: 'Antasida', price: 10000, qty: 1 }],
  },
  {
    id: 16,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Ready',
    customer: {
      id: 7,
      name: 'Apotek Prima',
      email: 'prima.apotek@gmail.com',
      phone: '+62 819 8765 4321',
      address: 'Jl. Papua No.8, Jayapura, Indonesia',
    },
    items: [{ id: 11, name: 'Chlorpheniramine', price: 12000, qty: 1 }],
  },
  {
    id: 17,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'In Transit',
    customer: {
      id: 9,
      name: 'Apotek Maju',
      email: 'maju.apotek@gmail.com',
      phone: '+62 822 4567 8901',
      address: 'Jl. Gajah Mada No.9, Pontianak, Indonesia',
    },
    items: [{ id: 12, name: 'Cetirizine', price: 14000, qty: 2 }],
  },
  {
    id: 18,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'In Transit',
    customer: {
      id: 11,
      name: 'Apotek Abadi',
      email: 'abadi.apotek@gmail.com',
      phone: '+62 823 5678 9012',
      address: 'Jl. Diponegoro No.10, Malang, Indonesia',
    },
    items: [{ id: 13, name: 'Loratadine', price: 16000, qty: 3 }],
  },
  {
    id: 19,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'In Transit',
    customer: {
      id: 12,
      name: 'Apotek Surya',
      email: 'surya.apotek@gmail.com',
      phone: '+62 824 6789 0123',
      address: 'Jl. Pasir Kaliki No.11, Bandung, Indonesia',
    },
    items: [{ id: 14, name: 'Ranitidine', price: 18000, qty: 1 }],
  },
  {
    id: 20,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Ready',
    customer: {
      id: 10,
      name: 'Apotek Sejahtera',
      email: 'sejahtera.apotek@gmail.com',
      phone: '+62 820 1234 5678',
      address: 'Jl. Sulawesi No.9, Palu, Indonesia',
    },
    items: [{ id: 15, name: 'Mefenamic Acid', price: 22000, qty: 2 }],
  },
  {
    id: 21,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Ready',
    customer: {
      id: 13,
      name: 'Apotek Berkat',
      email: 'berkat.apotek@gmail.com',
      phone: '+62 825 7890 1234',
      address: 'Jl. Cendrawasih No.12, Pekanbaru, Indonesia',
    },
    items: [{ id: 16, name: 'Ibuprofen', price: 20000, qty: 3 }],
  },
  {
    id: 22,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'In Transit',
    customer: {
      id: 14,
      name: 'Apotek Sentosa',
      email: 'sentosa.apotek@gmail.com',
      phone: '+62 826 8901 2345',
      address: 'Jl. Sisingamangaraja No.13, Medan, Indonesia',
    },
    items: [{ id: 17, name: 'Paracetamol', price: 15000, qty: 2 }],
  },
  {
    id: 23,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Ready',
    customer: {
      id: 15,
      name: 'Apotek Bahagia',
      email: 'bahagia.apotek@gmail.com',
      phone: '+62 827 9012 3456',
      address: 'Jl. Slamet Riyadi No.14, Solo, Indonesia',
    },
    items: [{ id: 18, name: 'Metformin', price: 18000, qty: 2 }],
  },
  {
    id: 24,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'In Transit',
    customer: {
      id: 16,
      name: 'Apotek Serasi',
      email: 'serasi.apotek@gmail.com',
      phone: '+62 828 0123 4567',
      address: 'Jl. Adi Sucipto No.15, Mataram, Indonesia',
    },
    items: [{ id: 19, name: 'Amlodipine', price: 20000, qty: 2 }],
  },
  {
    id: 25,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'Delivered',
    customer: {
      id: 17,
      name: 'Apotek Mitra',
      email: 'mitra.apotek@gmail.com',
      phone: '+62 829 1234 5678',
      address: 'Jl. Diponegoro No.16, Denpasar, Indonesia',
    },
    items: [{ id: 20, name: 'Atorvastatin', price: 22000, qty: 1 }],
  },
  {
    id: 26,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Ready',
    customer: {
      id: 18,
      name: 'Apotek Damai',
      email: 'damai.apotek@gmail.com',
      phone: '+62 830 2345 6789',
      address: 'Jl. Teuku Umar No.17, Banda Aceh, Indonesia',
    },
    items: [{ id: 21, name: 'Glimepiride', price: 24000, qty: 3 }],
  },
  {
    id: 27,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'In Transit',
    customer: {
      id: 19,
      name: 'Apotek Sehat',
      email: 'sehat.apotek@gmail.com',
      phone: '+62 831 3456 7890',
      address: 'Jl. Gatot Subroto No.18, Jakarta, Indonesia',
    },
    items: [{ id: 22, name: 'Clopidogrel', price: 26000, qty: 2 }],
  },
  {
    id: 28,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Ready',
    customer: {
      id: 20,
      name: 'Apotek Harmoni',
      email: 'harmoni.apotek@gmail.com',
      phone: '+62 832 4567 8901',
      address: 'Jl. Jenderal Sudirman No.19, Manado, Indonesia',
    },
    items: [{ id: 23, name: 'Valsartan', price: 28000, qty: 1 }],
  },
  {
    id: 29,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Ready',
    customer: {
      id: 21,
      name: 'Apotek Mulia',
      email: 'mulia.apotek@gmail.com',
      phone: '+62 833 5678 9012',
      address: 'Jl. Rajawali No.20, Balikpapan, Indonesia',
    },
    items: [{ id: 24, name: 'Losartan', price: 30000, qty: 2 }],
  },
  {
    id: 30,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Ready',
    customer: {
      id: 22,
      name: 'Apotek Sejati',
      email: 'sejati.apotek@gmail.com',
      phone: '+62 834 6789 0123',
      address: 'Jl. K.H. Ahmad Dahlan No.21, Tangerang, Indonesia',
    },
    items: [{ id: 25, name: 'Telmisartan', price: 32000, qty: 1 }],
  },
  {
    id: 31,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'In Transit',
    customer: {
      id: 23,
      name: 'Apotek Amanah',
      email: 'amanah.apotek@gmail.com',
      phone: '+62 835 7890 1234',
      address: 'Jl. Jenderal Sudirman No.22, Palembang, Indonesia',
    },
    items: [{ id: 26, name: 'Ramipril', price: 34000, qty: 2 }],
  },
  {
    id: 32,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'In Transit',
    customer: {
      id: 24,
      name: 'Apotek Bintang',
      email: 'bintang.apotek@gmail.com',
      phone: '+62 836 8901 2345',
      address: 'Jl. Merdeka No.23, Padang, Indonesia',
    },
    items: [{ id: 27, name: 'Enalapril', price: 36000, qty: 1 }],
  },
  {
    id: 33,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-13',
    status: 'Ready',
    customer: {
      id: 25,
      name: 'Apotek Tulus',
      email: 'tulus.apotek@gmail.com',
      phone: '+62 837 9012 3456',
      address: 'Jl. K.H. Wahid Hasyim No.24, Jakarta, Indonesia',
    },
    items: [{ id: 28, name: 'Furosemide', price: 38000, qty: 2 }],
  },
  {
    id: 34,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'In Transit',
    customer: {
      id: 26,
      name: 'Apotek Jaya',
      email: 'jaya.apotek@gmail.com',
      phone: '+62 838 0123 4567',
      address: 'Jl. Pemuda No.25, Semarang, Indonesia',
    },
    items: [{ id: 29, name: 'Spironolactone', price: 40000, qty: 1 }],
  },
  {
    id: 35,
    date: '2024-04-05T09:00:00',
    ETA: '2024-04-12',
    status: 'Ready',
    customer: {
      id: 27,
      name: 'Apotek Sehat Sentosa',
      email: 'sehat.sentosa@gmail.com',
      phone: '+62 839 1234 5678',
      address: 'Jl. Sultan Agung No.26, Medan, Indonesia',
    },
    items: [{ id: 30, name: 'Hydrochlorothiazide', price: 42000, qty: 2 }],
  },
]

export const troubles = [
  {
    id: 1,
    name: 'Raka Satya Prasasta',
    email: 'raka.satya@gmail.com',
    phone: '+62 812 7113 9285',
    location: 'Jl. Sudirman, Jakarta',
    datetime: '2024-10-03T09:10',
    description: 'Vehicle breakdown on the highway.',
    status: 'Pending',
  },
  {
    id: 2,
    name: 'Dewi Saraswati',
    email: 'dewi.saraswati@gmail.com',
    phone: '+62 813 4567 1234',
    location: 'Jl. Basuki Rahmat, Surabaya',
    datetime: '2024-10-03T11:20',
    description: 'Flat tire, needs assistance.',
    status: 'Responding',
  },
  {
    id: 3,
    name: 'Budi Santoso',
    email: 'budi.santoso@gmail.com',
    phone: '+62 814 6789 9876',
    location: 'Jl. Braga, Bandung',
    datetime: '2024-10-03T14:30',
    description: 'Engine overheating, pulled over.',
    status: 'Resolved',
  },
  {
    id: 4,
    name: 'Siti Aisyah',
    email: 'siti.aisyah@gmail.com',
    phone: '+62 815 2345 6789',
    location: 'Jl. Malioboro, Yogyakarta',
    datetime: '2024-10-04T08:15',
    description: 'Fuel leak detected, needs repair.',
    status: 'Pending',
  },
  {
    id: 5,
    name: 'Agus Setiawan',
    email: 'agus.setiawan@gmail.com',
    phone: '+62 816 3456 7890',
    location: 'Jl. Pandanaran, Semarang',
    datetime: '2024-10-04T10:40',
    description: 'Brake failure, unable to continue.',
    status: 'Responding',
  },
  {
    id: 6,
    name: 'Maya Dewi',
    email: 'maya.dewi@gmail.com',
    phone: '+62 817 4567 8901',
    location: 'Jl. Sisingamangaraja, Medan',
    datetime: '2024-10-05T12:50',
    description: 'Accident on the road, minor injuries.',
    status: 'Resolved',
  },
  {
    id: 7,
    name: 'Roni Pratama',
    email: 'roni.pratama@gmail.com',
    phone: '+62 818 5678 9012',
    location: 'Jl. Pettarani, Makassar',
    datetime: '2024-10-05T15:30',
    description: 'Lost GPS signal, unable to navigate.',
    status: 'Pending',
  },
  {
    id: 8,
    name: 'Lina Kurniawati',
    email: 'lina.kurniawati@gmail.com',
    phone: '+62 819 6789 0123',
    location: 'Jl. Diponegoro, Denpasar',
    datetime: '2024-10-06T09:20',
    description: 'Cargo shift, needs to be secured.',
    status: 'Responding',
  },
  {
    id: 9,
    name: 'Adi Putra',
    email: 'adi.putra@gmail.com',
    phone: '+62 820 7890 1234',
    location: 'Jl. MT Haryono, Balikpapan',
    datetime: '2024-10-06T11:45',
    description: 'Engine stalling, needs diagnosis.',
    status: 'Pending',
  },
  {
    id: 10,
    name: 'Tari Puspita',
    email: 'tari.puspita@gmail.com',
    phone: '+62 821 8901 2345',
    location: 'Jl. Jenderal Sudirman, Palembang',
    datetime: '2024-10-07T13:10',
    description: "Battery failure, vehicle won't start.",
    status: 'Resolved',
  },
]

export const items = [
  {
    id: 1,
    name: 'Metformin Hydrochloride',
    weight: 0.1,
    price: 71268,
    stock: 80,
  },
  {
    id: 2,
    name: 'Spinach',
    weight: 1.0,
    price: 154573,
    stock: 87,
  },
  {
    id: 3,
    name: 'Dextrose Monohydrate, Sodium Chloride, Sodium Lactate, Calcium Chloride, Magnesium Chloride',
    weight: 0.6,
    price: 23535,
    stock: 78,
  },
  {
    id: 4,
    name: 'Antihemophilic Factor/von Willebrand Factor Complex (Human)',
    weight: 2.8,
    price: 127973,
    stock: 72,
  },
  {
    id: 5,
    name: 'OCTINOXATE and TITANIUM DIOXIDE',
    weight: 2.6,
    price: 100340,
    stock: 89,
  },
  {
    id: 6,
    name: 'Trandolapril',
    weight: 2.1,
    price: 12179,
    stock: 99,
  },
  {
    id: 7,
    name: 'ciprofloxacin hydrochloride',
    weight: 0.2,
    price: 292295,
    stock: 93,
  },
  {
    id: 8,
    name: 'potassium chloride',
    weight: 1.1,
    price: 180837,
    stock: 99,
  },
  {
    id: 9,
    name: 'MINERAL OIL,PETROLATUM,PHENYLEPHRINE',
    weight: 2.6,
    price: 243880,
    stock: 77,
  },
  {
    id: 10,
    name: 'White Alder',
    weight: 1.6,
    price: 283928,
    stock: 89,
  },
]
export const vehicles = [
  {
    id: 1,
    deliveryID: 'D001',
    weight: 1200,
    maxWeight: 2000,
    capacity: 5000,
    status: 'In Transit',
    plateNumber: 'AB 123 CD',
    refrigerated: true,
    imgUrl: truck2d,
  },
  {
    id: 2,
    deliveryID: 'D002',
    weight: 1500,
    maxWeight: 2500,
    capacity: 6000,
    status: 'In Transit',
    plateNumber: 'EF 456 GH',
    imgUrl: scooter2d,
  },
  {
    id: 3,
    deliveryID: 'D003',
    weight: 1100,
    maxWeight: 2000,
    capacity: 5500,
    status: 'ready',
    plateNumber: 'IJ 789 KL',
    refrigerated: false,
    imgUrl: truck2d,
  },
  {
    id: 4,
    deliveryID: 'D004',
    weight: 1300,
    maxWeight: 2100,
    capacity: 5200,
    status: 'maintenance',
    plateNumber: 'MN 012 OP',
    imgUrl: scooter2d,
  },
  {
    id: 5,
    deliveryID: 'D005',
    weight: 1400,
    maxWeight: 2300,
    capacity: 5800,
    status: 'available',
    plateNumber: 'QR 345 ST',
    refrigerated: true,
    imgUrl: truck2d,
  },
  {
    id: 6,
    deliveryID: 'D006',
    weight: 1600,
    maxWeight: 2600,
    capacity: 6000,
    status: 'In Transit',
    plateNumber: 'UV 678 WX',
    imgUrl: scooter2d,
  },
  {
    id: 7,
    deliveryID: 'D007',
    weight: 1250,
    maxWeight: 2200,
    capacity: 5500,
    status: 'ready',
    plateNumber: 'YZ 901 AB',
    refrigerated: true,
    imgUrl: truck2d,
  },
  {
    id: 8,
    deliveryID: 'D008',
    weight: 1350,
    maxWeight: 2100,
    capacity: 5700,
    status: 'maintenance',
    plateNumber: 'CD 234 EF',
    imgUrl: scooter2d,
  },
  {
    id: 9,
    deliveryID: 'D009',
    weight: 1450,
    maxWeight: 2400,
    capacity: 5900,
    status: 'available',
    plateNumber: 'GH 567 IJ',
    refrigerated: false,
    imgUrl: truck2d,
  },
  {
    id: 10,
    deliveryID: 'D010',
    weight: 1550,
    maxWeight: 2500,
    capacity: 6000,
    status: 'In Transit',
    plateNumber: 'KL 890 MN',
    imgUrl: scooter2d,
  },
  {
    id: 11,
    deliveryID: 'D011',
    weight: 1150,
    maxWeight: 2100,
    capacity: 5400,
    status: 'ready',
    plateNumber: 'OP 123 QR',
    refrigerated: false,
    imgUrl: truck2d,
  },
  {
    id: 12,
    deliveryID: 'D012',
    weight: 1250,
    maxWeight: 2200,
    capacity: 5500,
    status: 'maintenance',
    plateNumber: 'ST 456 UV',
    imgUrl: scooter2d,
  },
  {
    id: 13,
    deliveryID: 'D013',
    weight: 1300,
    maxWeight: 2300,
    capacity: 5600,
    status: 'available',
    plateNumber: 'WX 789 YZ',
    refrigerated: false,
    imgUrl: truck2d,
  },
  {
    id: 14,
    deliveryID: 'D014',
    weight: 1400,
    maxWeight: 2400,
    capacity: 5800,
    status: 'In Transit',
    plateNumber: 'AB 012 CD',
    imgUrl: scooter2d,
  },
  {
    id: 15,
    deliveryID: 'D015',
    weight: 1500,
    maxWeight: 2500,
    capacity: 5900,
    status: 'ready',
    plateNumber: 'EF 345 GH',
    refrigerated: true,
    imgUrl: truck2d,
  },
  {
    id: 16,
    deliveryID: 'D016',
    weight: 1600,
    maxWeight: 2600,
    capacity: 6000,
    status: 'maintenance',
    plateNumber: 'IJ 678 KL',
    imgUrl: scooter2d,
  },
  {
    id: 17,
    deliveryID: 'D017',
    weight: 1700,
    maxWeight: 2700,
    capacity: 6100,
    status: 'available',
    plateNumber: 'MN 901 OP',
    refrigerated: false,
    imgUrl: truck2d,
  },
  {
    id: 18,
    deliveryID: 'D018',
    weight: 1800,
    maxWeight: 2800,
    capacity: 6200,
    status: 'In Transit',
    plateNumber: 'QR 234 ST',
    imgUrl: scooter2d,
  },
  {
    id: 19,
    deliveryID: 'D019',
    weight: 1900,
    maxWeight: 2900,
    capacity: 6300,
    status: 'ready',
    plateNumber: 'UV 567 WX',
    refrigerated: false,
    imgUrl: truck2d,
  },
  {
    id: 20,
    deliveryID: 'D020',
    weight: 2000,
    maxWeight: 3000,
    capacity: 6400,
    status: 'maintenance',
    plateNumber: 'YZ 890 AB',
    imgUrl: scooter2d,
  },
]

export const employees = [
  {
    id: 1,
    name: 'John Doe',
    role: 'Admin',
    status: 'Active',
    email: 'john.doe@gmail.com',
    phone: '+62 812 3456 7890',
    pfp: 'pfp.png',
  },
  {
    id: 2,
    name: 'Jane Smith',
    role: 'Driver',
    status: 'Idle',
    email: 'jane.smith@gmail.com',
    phone: '+62 813 2345 6789',
    pfp: 'pfp.png',
  },
  {
    id: 3,
    name: 'Alice Johnson',
    role: 'Packer',
    status: 'Off Duty',
    email: 'alice.johnson@gmail.com',
    phone: '+62 814 1234 5678',
    pfp: 'pfp.png',
  },
  {
    id: 4,
    name: 'Bob Brown',
    role: 'Admin',
    status: 'Inactive',
    email: 'bob.brown@gmail.com',
    phone: '+62 815 9876 5432',
    pfp: 'pfp.png',
  },
  {
    id: 5,
    name: 'Charlie Davis',
    role: 'Driver',
    status: 'En Route',
    email: 'charlie.davis@gmail.com',
    phone: '+62 816 6543 2109',
    pfp: 'pfp.png',
  },
  {
    id: 6,
    name: 'Diana Evans',
    role: 'Packer',
    status: 'Idle',
    email: 'diana.evans@gmail.com',
    phone: '+62 817 7654 3210',
    pfp: 'pfp.png',
  },
  {
    id: 7,
    name: 'Edward White',
    role: 'Admin',
    status: 'Idle',
    email: 'edward.white@gmail.com',
    phone: '+62 818 8765 4321',
    pfp: 'pfp.png',
  },
  {
    id: 8,
    name: 'Fiona Black',
    role: 'Driver',
    status: 'Off Duty',
    email: 'fiona.black@gmail.com',
    phone: '+62 819 1234 5678',
    pfp: 'pfp.png',
  },
  {
    id: 9,
    name: 'George Miller',
    role: 'Packer',
    status: 'Assigned',
    email: 'george.miller@gmail.com',
    phone: '+62 820 2345 6789',
    pfp: 'pfp.png',
  },
  {
    id: 10,
    name: 'Hannah Clark',
    role: 'Driver',
    status: 'Idle',
    email: 'hannah.clark@gmail.com',
    phone: '+62 821 3456 7890',
    pfp: 'pfp.png',
  },
  {
    id: 11,
    name: 'Ian Scott',
    role: 'Driver',
    status: 'Available',
    email: 'ian.scott@gmail.com',
    phone: '+62 822 4567 8901',
    pfp: 'pfp.png',
  },
  {
    id: 12,
    name: 'Julia Adams',
    role: 'Packer',
    status: 'Loading',
    email: 'julia.adams@gmail.com',
    phone: '+62 823 5678 9012',
    pfp: 'pfp.png',
  },
  {
    id: 13,
    name: 'Kevin Parker',
    role: 'Driver',
    status: 'Assigned',
    email: 'kevin.parker@gmail.com',
    phone: '+62 824 6789 0123',
    pfp: 'pfp.png',
  },
  {
    id: 14,
    name: 'Laura Turner',
    role: 'Driver',
    status: 'Idle',
    email: 'laura.turner@gmail.com',
    phone: '+62 825 7890 1234',
    pfp: 'pfp.png',
  },
  {
    id: 15,
    name: 'Michael Roberts',
    role: 'Packer',
    status: 'Available',
    email: 'michael.roberts@gmail.com',
    phone: '+62 826 8901 2345',
    pfp: 'pfp.png',
  },
  {
    id: 16,
    name: 'Nancy Wilson',
    role: 'Driver',
    status: 'Off Duty',
    email: 'nancy.wilson@gmail.com',
    phone: '+62 827 9012 3456',
    pfp: 'pfp.png',
  },
  {
    id: 17,
    name: 'Oscar Hughes',
    role: 'Driver',
    status: 'Assigned',
    email: 'oscar.hughes@gmail.com',
    phone: '+62 828 0123 4567',
    pfp: 'pfp.png',
  },
  {
    id: 18,
    name: 'Patricia James',
    role: 'Packer',
    status: 'Loading',
    email: 'patricia.james@gmail.com',
    phone: '+62 829 1234 5678',
    pfp: 'pfp.png',
  },
  {
    id: 19,
    name: 'Quinn Lee',
    role: 'Driver',
    status: 'Available',
    email: 'quinn.lee@gmail.com',
    phone: '+62 830 2345 6789',
    pfp: 'pfp.png',
  },
  {
    id: 20,
    name: 'Rachel Walker',
    role: 'Driver',
    status: 'En Route',
    email: 'rachel.walker@gmail.com',
    phone: '+62 831 3456 7890',
    pfp: 'pfp.png',
  },
]

export const jobRoles = [
  {
    id: 1,
    role: 'Driver',
    responsibility:
      'Drivers transport goods or passengers safely and efficiently adhering to traffic laws, and ensure timely deliveries.',
  },
  {
    id: 2,
    role: 'Packer',
    responsibility:
      'The packer securely and accurately packs items into vehicles, collaborating with the team for smooth delivery.',
  },
]

export const workTypes = [
  {
    id: 1,
    type: 'Part-Time',
    responsibility:
      'Part-Time Employees work flexible hours, contributing to tasks based on the roles selected',
  },
  {
    id: 2,
    type: 'Full-Time',
    responsibility:
      'Full-Time Employees work regular full-time hours, providing consistent support to the team.',
  },
]
export const customers = [
  {
    id: 1,
    username: 'ogomm0',
    password: 'gllgaoyG{?',
    name: 'Ogdan Gomm',
    email: 'ogomm0@xing.com',
    phone: '+216 224 980 9814',
    address: '3636 South Alley',
    DateofBirth: '05/01/1991',
    balance: 660764,
  },
  {
    id: 2,
    username: 'bedelheid1',
    password: "krzeoyvQ,p4'",
    name: 'Bogey Edelheid',
    email: 'bedelheid1@facebook.com',
    phone: '+48 552 898 8322',
    address: '842 Vidon Terrace',
    DateofBirth: '24/03/1999',
    balance: 273454,
  },
  {
    id: 3,
    username: 'mpilger2',
    password: 'mazhoiyHZry2%',
    name: 'Morgen Pilger',
    email: 'mpilger2@senate.gov',
    phone: '+358 914 969 5199',
    address: '22 Mccormick Way',
    DateofBirth: '31/08/2005',
    balance: 780656,
  },
  {
    id: 4,
    username: 'fyannikov3',
    password: 'yjcriumFm',
    name: 'Forbes Yannikov',
    email: 'fyannikov3@time.com',
    phone: '+996 575 978 1337',
    address: '0361 Twin Pines Way',
    DateofBirth: '23/01/1994',
    balance: 319720,
  },
  {
    id: 5,
    username: 'lhinrich4',
    password: 'afffnlxIC{0ogvS',
    name: 'Lenore Hinrich',
    email: 'lhinrich4@so-net.ne.jp',
    phone: '+62 712 805 0876',
    address: '8845 Kipling Trail',
    DateofBirth: '25/01/2000',
    balance: 233644,
  },
  {
    id: 6,
    username: 'bmcdavitt5',
    password: 'phtadzlH\\H',
    name: 'Beniamino McDavitt',
    email: 'bmcdavitt5@spotify.com',
    phone: '+389 149 191 4084',
    address: '379 Bartelt Circle',
    DateofBirth: '14/03/1998',
    balance: 164594,
  },
  {
    id: 7,
    username: 'srosewarne6',
    password: 'siybkikI>{aW}h',
    name: 'Saunders Rosewarne',
    email: 'srosewarne6@mac.com',
    phone: '+63 250 322 7537',
    address: '2090 Huxley Trail',
    DateofBirth: '05/11/2004',
    balance: 951272,
  },
  {
    id: 8,
    username: 'ybrettle7',
    password: 'vbigcduY',
    name: 'Yoshiko Brettle',
    email: 'ybrettle7@slideshare.net',
    phone: '+7 181 763 6200',
    address: '0 Tennessee Center',
    DateofBirth: '13/09/1993',
    balance: 235006,
  },
  {
    id: 9,
    username: 'rshotter8',
    password: 'rpqdcqyC@E',
    name: 'Ray Shotter',
    email: 'rshotter8@oracle.com',
    phone: '+34 289 515 7045',
    address: '33745 Mallard Trail',
    DateofBirth: '31/05/1999',
    balance: 747162,
  },
  {
    id: 10,
    username: 'starbard9',
    password: 'suacofsY(LdXuUR',
    name: 'Shana Tarbard',
    email: 'starbard9@prweb.com',
    phone: '+355 519 555 1960',
    address: '6102 Corscot Circle',
    DateofBirth: '10/11/2002',
    balance: 315775,
  },
]

export const driverStats = [
  {
    id: 'driverStats-1',
    title: 'Days on the Road',
    value: 61,
  },
  {
    id: 'driverStats-2',
    title: 'Completed Orders',
    value: 48,
  },
  {
    id: 'driverStats-3',
    title: 'Orders Delivered on Time',
    value: 42,
  },
  {
    id: 'driverStats-4',
    title: 'Status: En Route',
    value: 'Execute Order #78',
  },
]

export const driverRecentDeliveries = [
  {
    id: 1,
    date: '02-06-2024',
    totalRecipients: 6,
    totalKm: 15,
    totalWeight: 27,
  },
  {
    id: 2,
    date: '02-06-2024',
    totalRecipients: 6,
    totalKm: 15,
    totalWeight: 27,
  },
  {
    id: 3,
    date: '02-06-2024',
    totalRecipients: 6,
    totalKm: 15,
    totalWeight: 27,
  },
  {
    id: 4,
    date: '02-06-2024',
    totalRecipients: 6,
    totalKm: 15,
    totalWeight: 27,
  },
  {
    id: 5,
    date: '02-06-2024',
    totalRecipients: 6,
    totalKm: 15,
    totalWeight: 27,
  },
]

export const driverPersonalInfo = [
  {
    id: 1,
    img: 'pfp.png',
    firstName: 'John',
    lastName: 'Smith',
    gender: 'Male',
    email: 'johnsmith@gmail.com',
    birthday: '03-03-2024',
    age: '20',
    phone: '+62 812-7113-9285',
    employmentType: 'Full-Time',
    employmentDate: '21-02-2022',
    address:
      'Dublin village, Braginsky district, Gomel region, Republic of Belarus',
  },
]
