export const containerList = [
  {
    id: 1,
  },
  {
    id: 2,
  },
]

export const containerSize = [
  {
    size_x: 150,
    size_y: 150,
    size_z: 150,
  },
]

export const packData = [
  {
    shipment_id: 1,
    product_code: 'A3 - Medium Parcel *',
    insertion_order: 1,
    pos_x: 0,
    pos_y: 0,
    pos_z: 0,
    size_x: 31,
    size_y: 46,
    size_z: 26,
  },
  {
    shipment_id: 1,
    product_code: 'LAUN007',
    insertion_order: 2,
    pos_x: 31,
    pos_y: 0,
    pos_z: 0,
    size_x: 111,
    size_y: 11,
    size_z: 2,
  },
  {
    shipment_id: 1,
    product_code: 'DIAC015',
    insertion_order: 3,
    pos_x: 31,
    pos_y: 11,
    pos_z: 0,
    size_x: 39,
    size_y: 9,
    size_z: 8,
  },
  {
    shipment_id: 1,
    product_code: 'SEAL002',
    insertion_order: 4,
    pos_x: 70,
    pos_y: 11,
    pos_z: 0,
    size_x: 15,
    size_y: 15,
    size_z: 14,
  },
  {
    shipment_id: 1,
    product_code: 'SENT002',
    insertion_order: 5,
    pos_x: 85,
    pos_y: 11,
    pos_z: 0,
    size_x: 12,
    size_y: 12,
    size_z: 9,
  },
  {
    shipment_id: 1,
    product_code: 'Removals',
    insertion_order: 6,
    pos_x: 97,
    pos_y: 11,
    pos_z: 0,
    size_x: 39,
    size_y: 58,
    size_z: 38,
  },
  {
    shipment_id: 1,
    product_code: 'LAUN033',
    insertion_order: 7,
    pos_x: 0,
    pos_y: 69,
    pos_z: 0,
    size_x: 111,
    size_y: 11,
    size_z: 2,
  },
  {
    shipment_id: 1,
    product_code: 'NONC037',
    insertion_order: 8,
    pos_x: 31,
    pos_y: 26,
    pos_z: 0,
    size_x: 40,
    size_y: 30,
    size_z: 20,
  },
  {
    shipment_id: 1,
    product_code: 'STER017',
    insertion_order: 9,
    pos_x: 71,
    pos_y: 26,
    pos_z: 0,
    size_x: 21,
    size_y: 25,
    size_z: 21,
  },
  {
    shipment_id: 1,
    product_code: 'SAFE019',
    insertion_order: 10,
    pos_x: 136,
    pos_y: 11,
    pos_z: 0,
    size_x: 12,
    size_y: 12,
    size_z: 10,
  },
  {
    shipment_id: 1,
    product_code: 'NUTR011',
    insertion_order: 11,
    pos_x: 136,
    pos_y: 23,
    pos_z: 0,
    size_x: 10,
    size_y: 14,
    size_z: 10,
  },
  {
    shipment_id: 1,
    product_code: 'LAUN045',
    insertion_order: 12,
    pos_x: 0,
    pos_y: 80,
    pos_z: 0,
    size_x: 111,
    size_y: 11,
    size_z: 2,
  },
  {
    shipment_id: 1,
    product_code: 'INCI005',
    insertion_order: 13,
    pos_x: 0,
    pos_y: 91,
    pos_z: 0,
    size_x: 54,
    size_y: 21,
    size_z: 13,
  },
  {
    shipment_id: 1,
    product_code: 'Medium Parcel',
    insertion_order: 14,
    pos_x: 0,
    pos_y: 46,
    pos_z: 0,
    size_x: 21,
    size_y: 21,
    size_z: 21,
  },
  {
    shipment_id: 1,
    product_code: 'ZAMB002',
    insertion_order: 15,
    pos_x: 136,
    pos_y: 37,
    pos_z: 0,
    size_x: 10,
    size_y: 10,
    size_z: 6,
  },
  {
    shipment_id: 1,
    product_code: 'ROCU002',
    insertion_order: 16,
    pos_x: 136,
    pos_y: 47,
    pos_z: 0,
    size_x: 11,
    size_y: 9,
    size_z: 4,
  },
  {
    shipment_id: 1,
    product_code: 'RHIN003',
    insertion_order: 17,
    pos_x: 71,
    pos_y: 51,
    pos_z: 0,
    size_x: 11,
    size_y: 7,
    size_z: 6,
  },
  {
    shipment_id: 1,
    product_code: 'COUN001',
    insertion_order: 18,
    pos_x: 82,
    pos_y: 51,
    pos_z: 0,
    size_x: 12,
    size_y: 6,
    size_z: 3,
  },
  {
    shipment_id: 1,
    product_code: 'IMOD001',
    insertion_order: 19,
    pos_x: 21,
    pos_y: 46,
    pos_z: 0,
    size_x: 5,
    size_y: 11,
    size_z: 4,
  },
]
