export const container = {
  ID: 0,
  MaxWeight: 50,
  SizeX: 150,
  SizeY: 150,
  SizeZ: 150,
  Type: 'VehicleContainer',
  ItemList: [
    {
      ID: 1,
      Name: 'A3 - Medium Parcel *',
      PosX: 0,
      PosY: 0,
      PosZ: 0,
      SizeX: 31,
      SizeY: 46,
      SizeZ: 2,
      Type: 'Item',
    },
    {
      ID: 2,
      Name: 'LAUN007',
      PosX: 31,
      PosY: 0,
      PosZ: 0,
      SizeX: 111,
      SizeY: 11,
      SizeZ: 2,
      Type: 'Item',
    },
    {
      ID: 3,
      Name: 'DIAC015',
      PosX: 31,
      PosY: 11,
      PosZ: 0,
      SizeX: 39,
      SizeY: 9,
      SizeZ: 8,
      Type: 'Item',
    },
    {
      ID: 4,
      Name: 'SEAL002',
      PosX: 70,
      PosY: 11,
      PosZ: 0,
      SizeX: 15,
      SizeY: 15,
      SizeZ: 1,
      Type: 'Item',
    },
    {
      ID: 5,
      Name: 'SENT002',
      PosX: 85,
      PosY: 11,
      PosZ: 0,
      SizeX: 12,
      SizeY: 12,
      SizeZ: 9,
      Type: 'Item',
    },
    {
      ID: 6,
      Name: 'Removals',
      PosX: 97,
      PosY: 11,
      PosZ: 0,
      SizeX: 39,
      SizeY: 58,
      SizeZ: 3,
      Type: 'Item',
    },
    {
      ID: 7,
      Name: 'LAUN033',
      PosX: 0,
      PosY: 69,
      PosZ: 0,
      SizeX: 111,
      SizeY: 11,
      SizeZ: 2,
      Type: 'Item',
    },
    {
      ID: 8,
      Name: 'NONC037',
      PosX: 31,
      PosY: 26,
      PosZ: 0,
      SizeX: 40,
      SizeY: 30,
      SizeZ: 2,
      Type: 'Item',
    },
    {
      ID: 9,
      Name: 'STER017',
      PosX: 71,
      PosY: 26,
      PosZ: 0,
      SizeX: 21,
      SizeY: 25,
      SizeZ: 2,
      Type: 'Item',
    },
    {
      ID: 10,
      Name: 'SAFE019',
      PosX: 136,
      PosY: 11,
      PosZ: 0,
      SizeX: 12,
      SizeY: 12,
      SizeZ: 1,
      Type: 'Item',
    },
    {
      ID: 11,
      Name: 'NUTR011',
      PosX: 136,
      PosY: 23,
      PosZ: 0,
      SizeX: 10,
      SizeY: 14,
      SizeZ: 1,
      Type: 'Item',
    },
    {
      ID: 12,
      Name: 'LAUN045',
      PosX: 0,
      PosY: 80,
      PosZ: 0,
      SizeX: 111,
      SizeY: 11,
      SizeZ: 2,
      Type: 'Item',
    },
    {
      ID: 13,
      Name: 'INCI005',
      PosX: 0,
      PosY: 91,
      PosZ: 0,
      SizeX: 54,
      SizeY: 21,
      SizeZ: 1,
      Type: 'Item',
    },
    {
      ID: 14,
      Name: 'Medium Parcel',
      PosX: 0,
      PosY: 46,
      PosZ: 0,
      SizeX: 21,
      SizeY: 21,
      SizeZ: 2,
      Type: 'Item',
    },
    {
      ID: 15,
      Name: 'ZAMB002',
      PosX: 136,
      PosY: 37,
      PosZ: 0,
      SizeX: 10,
      SizeY: 10,
      SizeZ: 6,
      Type: 'Item',
    },
    {
      ID: 16,
      Name: 'ROCU002',
      PosX: 136,
      PosY: 47,
      PosZ: 0,
      SizeX: 11,
      SizeY: 9,
      SizeZ: 4,
      Type: 'Item',
    },
    {
      ID: 17,
      Name: 'RHIN003',
      PosX: 71,
      PosY: 51,
      PosZ: 0,
      SizeX: 11,
      SizeY: 7,
      SizeZ: 6,
      Type: 'Item',
    },
    {
      ID: 18,
      Name: 'COUN001',
      PosX: 82,
      PosY: 51,
      PosZ: 0,
      SizeX: 12,
      SizeY: 6,
      SizeZ: 3,
      Type: 'Item',
    },
    {
      ID: 19,
      Name: 'IMOD001',
      PosX: 21,
      PosY: 46,
      PosZ: 0,
      SizeX: 5,
      SizeY: 11,
      SizeZ: 4,
      Type: 'Item',
    },
  ],
}
