export const container = {
  ID: 0,
  MaxWeight: 50,
  SizeX: 150,
  SizeY: 150,
  SizeZ: 150,
  Type: 'VehicleContainer',
  ItemList: [
    {
      Type: 'Item',
      ID: 0,
      Name: 'Cardboard',
      SizeX: 22,
      SizeY: 31,
      SizeZ: 46,
      Weight: 1,
      PosX: 0,
      PosY: 0,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 1,
      Name: 'item',
      SizeX: 111,
      SizeY: 11,
      SizeZ: 2,
      Weight: 1,
      PosX: 0,
      PosY: 31,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 2,
      Name: 'item',
      SizeX: 39,
      SizeY: 9,
      SizeZ: 8,
      Weight: 1,
      PosX: 0,
      PosY: 42,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 3,
      Name: 'item',
      SizeX: 15,
      SizeY: 15,
      SizeZ: 1,
      Weight: 1,
      PosX: 0,
      PosY: 51,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 4,
      Name: 'item',
      SizeX: 12,
      SizeY: 12,
      SizeZ: 9,
      Weight: 1,
      PosX: 0,
      PosY: 66,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 5,
      Name: 'item',
      SizeX: 39,
      SizeY: 58,
      SizeZ: 3,
      Weight: 1,
      PosX: 0,
      PosY: 78,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 6,
      Name: 'item',
      SizeX: 111,
      SizeY: 11,
      SizeZ: 2,
      Weight: 1,
      PosX: 0,
      PosY: 136,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 7,
      Name: 'item',
      SizeX: 40,
      SizeY: 30,
      SizeZ: 2,
      Weight: 1,
      PosX: 22,
      PosY: 0,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 8,
      Name: 'item',
      SizeX: 21,
      SizeY: 25,
      SizeZ: 2,
      Weight: 1,
      PosX: 15,
      PosY: 51,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 9,
      Name: 'item',
      SizeX: 12,
      SizeY: 12,
      SizeZ: 1,
      Weight: 1,
      PosX: 36,
      PosY: 51,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 10,
      Name: 'item',
      SizeX: 10,
      SizeY: 14,
      SizeZ: 1,
      Weight: 1,
      PosX: 36,
      PosY: 63,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 11,
      Name: 'item',
      SizeX: 111,
      SizeY: 11,
      SizeZ: 2,
      Weight: 1,
      PosX: 39,
      PosY: 78,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 12,
      Name: 'item',
      SizeX: 54,
      SizeY: 21,
      SizeZ: 1,
      Weight: 1,
      PosX: 39,
      PosY: 89,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 13,
      Name: 'item',
      SizeX: 21,
      SizeY: 21,
      SizeZ: 2,
      Weight: 1,
      PosX: 39,
      PosY: 110,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 14,
      Name: 'item',
      SizeX: 10,
      SizeY: 10,
      SizeZ: 6,
      Weight: 1,
      PosX: 46,
      PosY: 63,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 15,
      Name: 'item',
      SizeX: 11,
      SizeY: 9,
      SizeZ: 4,
      Weight: 1,
      PosX: 48,
      PosY: 42,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 16,
      Name: 'item',
      SizeX: 12,
      SizeY: 6,
      SizeZ: 3,
      Weight: 1,
      PosX: 48,
      PosY: 51,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 17,
      Name: 'item',
      SizeX: 12,
      SizeY: 6,
      SizeZ: 3,
      Weight: 1,
      PosX: 56,
      PosY: 63,
      PosZ: 0,
    },
    {
      Type: 'Item',
      ID: 18,
      Name: 'item',
      SizeX: 5,
      SizeY: 11,
      SizeZ: 4,
      Weight: 1,
      PosX: 60,
      PosY: 42,
      PosZ: 0,
    },
  ],
}

export const cardboard = {
  ID: 1,
  SizeX: 22,
  SizeY: 31,
  SizeZ: 46,
  MaxWeight: 6,
  Type: 'CardboardContainer',
  ItemList: [
    {
      ID: 20,
      Name: 'ITEM001',
      PosX: 0,
      PosY: 0,
      PosZ: 0,
      SizeX: 15,
      SizeY: 22,
      SizeZ: 11,
    },
    {
      ID: 21,
      Name: 'ITEM002',
      PosX: 0,
      PosY: 0,
      PosZ: 11,
      SizeX: 10,
      SizeY: 10,
      SizeZ: 6,
    },
    {
      ID: 22,
      Name: 'ITEM003',
      PosX: 0,
      PosY: 22,
      PosZ: 0,
      SizeX: 16,
      SizeY: 9,
      SizeZ: 24,
    },
    {
      ID: 23,
      Name: 'ITEM004',
      PosX: 0,
      PosY: 10,
      PosZ: 11,
      SizeX: 15,
      SizeY: 11,
      SizeZ: 24,
    },
  ],
}
